[project]
name = "dns_analysis"
version = "0.1.0"
description = "Johnson's Final Assignment of Computer Networks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scapy>=2.6.1",
]
